### PR TITLE
Added Intro

### PR DESCRIPTION
**Pull request by simingg**

### CODE REVIEW

**Comment by Jcheez** [comment]
Hi,

your merge conflict exercise is not done / did not commit. Try submitting again when you are done with that.

**Comment by simingg** [comment]
> Hi,
> 
> your merge conflict exercise is not done / did not commit. Try submitting again when you are done with that.

**Comment by simingg** [comment]
hello @Jcheez is this considered done?

**Comment by Jcheez** [comment]
No. You needa refer to the merge conflict exercise in discovery, merging branches exercise

**Comment by simingg** [comment]
Hi, sorry for the late reply! Just did the merge exercise. Sorry i missed it out as i re-did it and forgot to start from the beginning

**Pull request merged**
